# message("COMPILE_PARAMETERS_IN = ${COMPILE_PARAMETERS_IN}")
# message("COMPILE_PARAMETERS_OUT = ${COMPILE_PARAMETERS_OUT}")

exec_program(
	"git"
	${CMAKE_CURRENT_SOURCE_DIR}
	ARGS "rev-parse HEAD"
	OUTPUT_VARIABLE GIT_COMMIT_HASH
	RESULT_VARIABLE GIT_COMMIT_HASH_RESULT)
		
if (GIT_COMMIT_HASH_RESULT AND NOT GIT_COMMIT_HASH_RESULT EQUAL 0)
	message(FATAL_ERROR "Git version error")
endif()

configure_file(${COMPILE_PARAMETERS_IN} ${COMPILE_PARAMETERS_OUT} @ONLY)
message("--- Generated ${COMPILE_PARAMETERS_OUT}")
